apiVersion: apps/v1
kind: Deployment
metadata:
  name: feats-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feats-backend
  template:
    metadata:
      labels:
        app: feats-backend
    spec:
      containers:
      - name: feats-backend
        image: feats-backend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8089 
        envFrom:
        - configMapRef:
            name: feats-backend-config
        env:
        - name: POSTGRES_HOST
          value: postgres

---
apiVersion: v1
kind: Service
metadata:
  name: feats-backend
spec:
  selector:
    app: feats-backend
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8089
  type: ClusterIP

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: feats-backend-config
data:
  POSTGRES_USER: "username"
  POSTGRES_PASSWORD: "password"
  POSTGRES_DB: "postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_LOCAL_IP: "localhost"
  POSTGRES_DOCKER_IP: "192.168.49.2"
  SPRING_PROFILES_ACTIVE: "docker"